substitutions:

  shutter_entity_1: "cover.menjador_1"
  shutter_entity_2: "cover.menjador_2"
  shutter_entity_3: "cover.menjador_3"
  shutter_entity_4: "cover.menjador_4"

  shutter_widget_name_1: "Menjador 1"
  shutter_widget_name_2: "Menjador 2"
  shutter_widget_name_3: "Menjador 3"
  shutter_widget_name_4: "Menjador 4"


  shutter_label_name_1: "Menjador 1"
  shutter_label_name_2: "Menjador 2"
  shutter_label_name_3: "Menjador 3"
  shutter_label_name_4: "Menjador 4"


packages:
  shutter_panel: !include shutter_panel.yaml

  shutter_1: !include
    file: shutter_widget.yaml
    vars:
      shutter_entity: "${shutter_entity_1}"
      shutter_widget_name: "${shutter_widget_name_1}"
      
  shutter_2: !include
    file: shutter_widget.yaml
    vars:
      shutter_entity: "${shutter_entity_2}"
      shutter_widget_name: "${shutter_widget_name_2}"
      
  shutter_3: !include
    file: shutter_widget.yaml
    vars:
      shutter_entity: "${shutter_entity_3}"
      shutter_widget_name: "${shutter_widget_name_3}"

  shutter_4: !include
    file: shutter_widget.yaml
    vars:
      shutter_entity: "${shutter_entity_4}"
      shutter_widget_name: "${shutter_widget_name_4}"

